# Generated by Django 4.2.13 on 2024-06-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['name']},
        ),
    ]
