# Generated by Django 4.2.13 on 2024-06-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournament_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='state',
            field=models.CharField(choices=[('setup', 'Setup'), ('playing', 'Playing'), ('finished', 'Finished')], default='setup', max_length=10),
        ),
    ]
