# Generated by Django 4.2.13 on 2024-05-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usertwofactorauthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertwofactorauthdata',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
