# Generated by Django 4.2.13 on 2024-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usertwofactorauthdata_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
