# Generated by Django 4.2.13 on 2024-05-24 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_is_2fa_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertwofactorauthdata',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
