# Generated by Django 4.2.13 on 2024-06-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userprofile_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='', max_length=5000),
        ),
    ]
