version: '3.8'

networks:
  transcendence:

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Docker/Dockerfile_backend
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
    networks:
      - transcendence
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - transcendence

  # check exposiong ports
  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./PostgreSQL/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - transcendence

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-data/:/var/lib/grafana
    networks:
      - transcendence
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./Docker/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    networks:
      - transcendence
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - transcendence

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    command:
      - '-port=8098'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    ports:
      - 8098:8098
    networks:
      - transcendence

  # check exposiong ports
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - transcendence
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Docker/Dockerfile_nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - transcendence
    volumes:
      - ./backend/static:/staticfiles
    depends_on:
      - prometheus
      - grafana
      - adminer
      - redis
      - database
      - backend

volumes:
  frontend:
    driver: local
  prometheus-data: {}
