# Generated by Django 4.2.13 on 2024-06-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='average_rally',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='max_rally',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='min_rally',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='is_win',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='opponent_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='user_score',
            field=models.IntegerField(null=True),
        ),
    ]
